
[general]
	rend_arrows = false
	waypoint_color = "255,255,0,255"
	chat_type_waypoint_rendering = 0
	stops_entity_death_animation = true
	draw_chat_waypoints = 54
	confirm_leader_commands = false
	invited_player_name = ""
	detect_reaper_armor = false
	party_and_warp_on_chat_message = ""
	skyblock_xp_gain_message = true
	treecap_timer = false
	waypoint_beacon_height = 71
	party_commands = true
	steak-able_vamp_hitbox = false

[kuudra]
	stop_rendering_mob_nametags_in_kuudra = false
	shows_kuudra = false
	supply_pearl_lineup = false
	custom_supply_drop_message = false
	"not_stunning?" = true
	accurate_supply_waypoints = false
	highlight_teammates_in_kuudra = false
	teammate_color = "255,106,0,255"
	"no_pre!_no_second!" = false
	supply_drop_waypoints = false
	draw_hitboxes_around_freshers = false
	breaking_piles = false
	build_helper = false
	stop_rendering_useless_perks = false
	notify_party_on_fresh = false

[hud]

	[hud.widget]
		custom_widget_text = "Players"
		frozen_corpse_widget = true
		trophy_fish_widget = false
		pet_widget = true
		stats_widget = true
		widget_display = true
		pest_widget = false
		commission_widget = true
		crop_milestone_widget = false
		custom_widget = true
		visitor_widget = false
		jacob_widget = false
		bestiary_widget = true
		powder_widget = true

	[hud.poison]
		poison_display = false

	[hud.clock]
		time_display = 1
		clock_display = true

	[hud.align]
		align_display = false
		highlight_players_in_align_radius = false

	[hud.legion]
		legion_display = false

	[hud.mana]
		mana_enchant_calc = false
		endstone_sword_party_notify = false
		cumulative_fero_mana = 0
		endstone_sword_mana_drain_range = false
		cumulative_strong_mana = 0

	[hud.blaze]
		blaze_display = false

	[hud.fatal_tempo]
		fatal_tempo_settings = 0
		fatal_tempo_timer_scale = 1.2
		fatal_tempo_display = false

	[hud.bestiary]
		mob_highlight_counter = false

	[hud.visitor]
		next_visitor_display = 0

	[hud.miniboss]
		miniboss_display = false

	[hud.champion]
		champion_display = false

	[hud.gyro]
		gyro_display = false
		mage_gyro = false

[bestiary]
	mob_esp = ""
	armor_stand_esp_color = "255,0,255,0"
	armor_stand_names_esp = ""
	player_esp_color = "255,255,0,255"
	mob_esp_color = "255,255,255,0"
	"matcho!" = false
	arachnes_keeper = false
	player_names_esp = ""

[crimson_isle]
	announce_vanquishers = false
	trophy_fish_session_counter = false
	announce_jawbus = false
	announce_plhlegblasts = false
	announce_thunder = false
	better_magma_boss_message = false

["beta_(wip)"]
	lapis_only = true
	gyro_range = true
	corpse_waypoints = true
	agro_range = false
	tracks_damage_armor_stands = false
	totem_color_opacity = 0.25
	agro_range_color = "255,255,0,0"
	totem_range = false
	gyro_color_opacity = 0.52307785
	agro_color_opacity = 0.5
	removed_boss_dialouge = true
	totem_range_options = 0
	gyro_range_color = "255,249,0,249"
	totem_range_color = "255,0,255,255"
	mineshaft_helper = true

[qol]
	toggle_block_highlight = true
	render_armor_bar = true
	remove_discord_warnings = true
	render_food_bar = true
	highlight_color = "255,254,0,255"
	disable_falling_blocks = true

